### ISSUE TITLE
Better illustrations for Turing machines

### ISSUE THREAD

**Issue by rzach** [OpenLogicProject/OpenLogic#142]
Replace the Turing machine diagram in https://github.com/OpenLogicProject/OpenLogic/blob/master/content/turing-machines/machines-computations/introduction.tex with a nice diagram.

Add a diagram for composition of TMs in https://github.com/OpenLogicProject/OpenLogic/blob/master/content/turing-machines/machines-computations/combining-machines.tex (two blobs representing the transition diagrams, arrows from a bunch of "halting" states to the start state of the second machine, blob around the whole thing to indicate it's a new machine.

**Comment by pdaniell** [comment]
You can set me as the assignee, I will try to get this done over the next week

**Comment by pdaniell** [comment]
@rzach  I  was wondering if you had any suggestions about how the present diagram should be improved. I suppose I could try to transform the present 2d diagram to the handdrawn line style of the sets operations diagram. 

I also had a thought that maybe the figure should be an isometric diagram. Even though my own view is that the Turing machine is an abstract object (on account of its potentially infinite use of tape) it is usually explained as a kind of physical device. If we presented the control head as a sort of 3d box configured over the tape, maybe that could make that point visually.

**Comment by rzach** [comment]
I really liked the set diagrams and as you suggested it would be nice to have a uniform style for the illustrations. I vote for the first option: stylized 2d.

**Comment by pdaniell** [comment]
Do you want the strokes/blanks on the tape to be in the LaTeX font? I can make them line-drawn but of course they are not going to look exactly like the symbols in the text. I can put  Computer Modern in the EPS via a TTF I have of it (though the book itself doesn't seem to be usually typeset in CM). Or you think Tikz will be able to super impose the text itself

Presently I am just converting the first image into something that looks more like the function/sets diagrams. However, I wonder if there should be something more illustrative for the control head of the Turing Machine. Right now it's just a box with two arrows. I am not completely sure how to make it more engaging --- sometimes Turing machines are described with the control head "containing" the computer code, i.e. the state diagram. I suppose we could make it bigger and have a very schematic picture of a transition diagram within the box. Maybe just an unlabeled light gray graph (it wouldn't be legible what the program is). The diagram would probably be bigger than it is presently.

**Comment by pdaniell** [comment]
BTW, here is what I have so far (there are lacunae for the text labels/strokes/spaces):

https://github.com/pdaniell/logic.open/blob/master/assets/diagrams/turing-machines/gen/introduction-diagram.png

I am not so happy with it. It has the virtue that it seems to have the color scheme of the other diagrams but I don't know what a student would think of this diagram -- the arrow does suggest the cell is being scanned but it don't know if a novice would really "get it."

**Comment by pdaniell** [comment]
It occurred to me that maybe what the illustration needs is a side-by-side sort of split where the left portion shows the control head before it has done something and then a right hand portion after it has moved and done something. Then the caption can read "(a) before the machine has written a stroke on cell 2" (b) "after it has  written a stroke". That would indicate motion in a way better than the arrows.

**Comment by rzach** [comment]
That is a great idea! I was also thinking the machine (in the "before" state) could have a thought bubble with the instruction it's about to execute?

Re: text in the image. I haven't tried it yet but I assume Tikz can put the text in itself (in whatever typeface is used to compile).

**Comment by rzach** [comment]
I'm about to send the Fall edition of our textbook to the printer (ie Amazon). Should I wait? Are you close? (No pressure!)

**Comment by pdaniell** [comment]
Hi Richard -- a little swamped this week because I've got a thesis chapter due. Probably shouldn't wait --- I will think more about how to do the Turing machine illustration and probably have it after the 30th.

**Comment by rzach** [comment]
We can wait! Thanks!

**Comment by pdaniell** [comment]
Hi Richard, 

Sorry for the delay. I've got a new proposal for the introductory Turing machine diagram. I've placed the image on my personal fork of the open logic project, in the assets directory. 

https://github.com/pdaniell/logic.open/blob/master/assets/diagrams/turing-machines/gen/introduction-diagram.png

There is an SVG in that directory as well.

I thought the idea was not to just show a single Turing machine in a single state but show a few states, so we can get the sense that it is moving around and modifying the tape.  Hence, the accompanying text will presumably have to be changed to explain the three different stages. (I had to change the contents of the tape from your original diagram -- I felt I didn't need to put so many squares in the diagram since it would make it look too busy.)

I also realized placing the control head below or above the tape was a little confusing visually, so what I have attempted to do is use the alpha channel so the head appears above the tape but scanning its contents below. I think this style could be repurposed for other diagrams. 

Paul

**Comment by nicolewyatt** [comment]
I really like this.


--

Nicole Wyatt

Department Head, Philosophy

University of Calgary


nicole.wyatt@ucalgary.ca

+1 403 220 3166

________________________________

**Comment by rzach** [comment]
Ah running up against that scaling issue again. Can you add the .ai file, that may help.

**Comment by pdaniell** [comment]
It's checked in here

https://github.com/pdaniell/logic.open/tree/master/assets/diagrams/turing-machines

**Comment by pdaniell** [comment]
By the way, can you send a screen shot of the scaling issue? Maybe if I know what's going on, I can try to fix it in the AI and the generated artifacts (SVG, PNG, etc). You can just attach it to this bug.

**Comment by rzach** [comment]
I fixed it by scaling the SVG in Inkscape. It's a problem with \tikzscale.

By the way, the 1's, 0's, and q's are all converted to paths, right? Since the diagram is followed by text that explains what's happening, I'll have to adjust that text. But the text also makes reference to \TMstroke and \TMblank and if those are redefined, the diagram should change with it. I can put those in in the SVG but it may be better to do it in the original AI and generate a new SVG

**Comment by pdaniell** [comment]
Yes everything is converted to outlines -- the font was actually the TTF version of Computer Modern. My guess is the TMStroke and TMblank are redefined, the easier way about it is to simply change the original AI. (That will mean, of course, checking in the AIs in addition to the SVGs somewhere in the source tree). 

I am guessing it will be a lot of effort to try to center the new TMStrokes and TMblanks in the tape cells and try to simulate a font weight appropriate for filling the cells just by using TikZ. Moreover,  the control head looks like it's scanning the cell below because it has white rectangle with an alpha channel set to 40%. Would Tikz even be able to put a TMStroke or TMblank underneath that white rectangle? I'm not sure. 

I don't think there is much downside to using a font-face in the diagrams that is different from the text --- as long as it's consistent.

**Comment by rzach** [comment]
Hm, I was more worried about the actual symbols used, not so much the typeface. I played around with it. The alpha works fine. But the type size and alignment turns out to not work well at all. So I'll leave it as is.

**Comment by pdaniell** [comment]
I do sort of think the AI files should be checked in somewhere rather than the SVGs/TikZ --- just in case someone wants to edit them in the future. They are largeish files, however --- but they will allow for maximum latitude in editing in the future.

**Comment by pdaniell** [comment]
Should we close out this bug? I'm happy to make some more illustrations if give me an idea of what you want to draw,

**Comment by rzach** [comment]
Just trying to find the time to actually put it in and rewrite the text to match the new diagram.

**Comment by rzach** [comment]
Ok done with commit 7ed0717
