### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by alex-bender** [OpenLogicProject/OpenLogic#167]
Hey guys, seems that it's typo (iff), but i'm not sure:
https://github.com/OpenLogicProject/OpenLogic/blob/e5402bee7f84c3e72b937b48356efb68e0a7597a/content/sets-functions-relations/sets/basics.tex#L83

And thanks for that book. It's great!

*edited*
Shame on me, sorry for bothering.
https://en.m.wikipedia.org/wiki/If_and_only_if

**Comment by iblech** [comment]
Dear Alex! (I'm not a maintainer, just following along.)

I'd say shame on us for not explaining the term. Surely many people have fallen into this trap and I'd like to fix it, by shortly explaining the term. Maybe at exactly the position you pointed us to, because that seems to be the first occurence of that term.

Dear maintainers, would you like that?

If yes, then I could prepare a short pull request. Or Alex, you could do it, if you wanted to!

**Comment by rzach** [comment]
That's a good point. Problem is that people may want to (and do) arrange the material in a different order. So this is not guaranteed to be the first occurrence of "iff".

It could probably be explained in the "methods/proofs" chapter? Or, simply replaced by "if and only if" everywhere?

**Comment by iblech** [comment]
> That's a good point. Problem is that people may want to (and do) arrange the material in a different order. So this is not guaranteed to be the first occurrence of "iff".

Oh, right, of course.

> It could probably be explained in the "methods/proofs" chapter? Or, simply replaced by "if and only if" everywhere? 

There are currently 833 occurences of "iff" in the book. Personally, I'd continue to use that phrase, because it's well-established and we want to introduce students to our community. An explanation on the "methods/proofs" chapter sounds good!

**Comment by rzach** [comment]
Done! cfd8b42ce5fad6c8c81f8cfbaf667a52426fa8ed

**Comment by alex-bender** [comment]
Thanks guys!
